---
title: "git_00"
author: "Alex Moreno"
date: "Summer 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
’Twas brillig, and the slithy toves  
      Did gyre and gimble in the wabe:   
All mimsy were the borogoves,       
      And the mome raths outgrabe.  

“Beware the Jabberwock, my son!   

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Whose woods these are I think I know.  
His house is in the village, though;  
He will not see me stopping here  
To watch his woods fill up with snow.  

My little horse must think it queer  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Looking up at the stars, I know quite well  
That, for all they care, I can go to hell,  
But on earth indifference is the least  
We have to dread from man or beast.  

How should we like it were stars to burn  
With a passion for us we could not return?  
If equal affection cannot be,  
Let the more loving one be me.  

Admirer as I think I am  
Of stars that do not give a damn,  
I cannot, now I see them, say  
I missed one terribly all day.  

Were all stars to disappear or die,  
I should learn to look at an empty sky  
And feel its total dark sublime,  
Though this might take me a little time.  